[package]
name = "rarkeys"
version = "0.0.1"
authors = ["acolytec3"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
rsa = "0.9.2"
rand = "0.8.5"
pkcs8 = "0.10.2"
getrandom = { version = "0.2", features = ["js"] }